version: 2
project_name: kroki-cli

builds:
  - id: kroki-cli
    dir: .
    main: ./cmd/kroki-cli/main.go  # adjust path to your main package
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    format: tar.gz
    builds:
      - kroki-cli
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: reilee
    name: kroki-cli
